### ISSUE TITLE
Latest release? Global api-token

### ISSUE THREAD

**Issue by SoftXperience** [Thibauth/python-pushover#32]
Hi,
is this lib still maintained? The latest release was 0.4, but there are some commits after that.

This lib is used by a home-assistant component. The problem is that if I use multiple api-keys, in version 0.4 it seems to be stored globally, so not working.

But it seems that this is fixed on master branch. But I can't use and adopt it in home-assistant as there is no release after 0.4

**Comment by CMon** [comment]
Funny I just ran into the same problem, I worked around by not using the plugin, but using the rest api directly:
```
notify:
    - name: notifyGroup
      platform: rest
      method: POST
      resource: 'https://api.pushover.net/1/messages.json'
      message_param_name: message
      title_param_name: title
      data:
          user: <user/group key>
          token: <api key>
```
just a few lines more than the pushover api
